# -*- coding: utf-8 -*-
"""polarity.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AEny9JsJGpDXaNUIl6xe-DogiwPEur3s
"""

file_names = [x for x in os.listdir("datasets/EXTRACTED_FILINGS") if x.split('_')[1]=='10Q']
import pandas as pd
import numpy as np
df = pd.DataFrame()
df["filename"]= []  
df["item_1"] = []
df["item_1A"] = []
df["item_1B"] = []
df["item_2"] = []
df["item_3"] = []
df["item_4"] = []
df["item_5"] = []
df["item_6"] = []
df["item_7"] = []
df["item_7A"] = []
df["item_8"] = []
df["item_9"] = []
df["item_9A"] = []
df["item_9B"] = []
df["item_10"] = []
df["item_11"] = []
df["item_12"] = []
df["item_13"] = []
df["item_14"] = []
df["item_15"] = []

import json
import re
for f in file_names:
    f3 = open("datasets/EXTRACTED_FILINGS/"+f)
    data = json.load(f3)
    # temp = data['item_7']
    temp = re.sub(r"\\n", " ", data['item_7'])
    df = df.append({"filename":f,"item_1": data['item_1'],"item_1A": data['item_1A'],"item_1B": data['item_1B'],"item_2": data['item_2'],"item_3": data['item_3'],"item_4": data['item_4'],"item_5": data['item_5'], "item_6": data['item_6'],"item_7": temp, "item_7A": data['item_7A'],"item_8": data['item_8'],"item_9": data['item_9'],"item_9A": data['item_9A'],"item_9B": data['item_9B'],"item_10": data['item_10'],"item_11": data['item_11'],"item_12": data['item_12'],"item_13": data['item_13'],"item_14": data['item_14'],"item_15": data['item_15'], }, ignore_index= True)

df.drop(['item_7','item_7A', 'item_8', 'item_9',
       'item_9A', 'item_9B', 'item_10', 'item_11', 'item_12', 'item_13',
       'item_14', 'item_15'],axis=1,inplace=True)

df['text'] = df[['item_1', 'item_1A', 'item_1B', 'item_2', 'item_3',
       'item_4', 'item_5', 'item_6']].apply(lambda x: ' '.join(x), axis = 1)

df['polarity_score']=float(0)
# df['polarity_score']=[]
df['polarity_score'].astype("float")
for i in range(len(df)):
    arr=[]
    blob = TextBlob(df['text'][i])
    for sentence in blob.sentences:
        arr.append([sentence.sentiment.polarity])
    
    df['polarity_score'][i]=(np.array(arr).mean())

df.to_csv("10q_polarity.csv",index=False)