# -*- coding: utf-8 -*-
"""datawithfinalmetrics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13Vc_a0pyRXVGJ6UP-ZS3J_SX5BmwHhhO
"""

import numpy as np
import pandas as pd

scraped_customer_df=pd.read_csv("customers_scraped_google.csv",sep='|')
scraped_customer_df.head()

scraped_customer_df.shape

import torch

from transformers import pipeline

import huggingface

question_answerer = pipeline('question-answering')

question_answerer({
    'question': 'How many customers?',
    'context': scraped_customer_df['google_scraped_text'][80]})

scraped_customer_df['google_scraped_text'][80]

scraped_customer_df['google_scraped_text'][1]

scraped_customer_df.dtypes

arr = []
for i in range(len(scraped_customer_df)):
  context = str(scraped_customer_df['google_scraped_text'][i])
  temp2 = question_answerer({'question': 'How many customers?','context': context })
  scraped_customer_df['confidence_score'][i]=temp2['score']
  scraped_customer_df['answer'][i]=temp2['answer']
  # print(temp2['answer'])

temp=question_answerer({
    'question': 'How many customers?',
    'context': scraped_customer_df['google_scraped_text'][80]})

temp['score']

scraped_customer_df.head(5)

scraped_customer_df.to_csv("scraped_answer.csv",index=False)

pd.set_option('display.max_columns', None)  # or 1000
pd.set_option('display.max_rows', None)  # or 1000
pd.set_option('display.max_colwidth', None)  # or 199

scraped_customer_df.head()

import seaborn as sns
sns.distplot(x=scraped_customer_df['confidence_score'])

# scraped_customer_df[[scraped_customer_df['confidence_score']<0.1 and scraped_customer_df['confidence_score']>0.05]]
# scraped_customer_df.loc[(scraped_customer_df['confidence_score']<0.1) and (scraped_customer_df['confidence_score']>0.05)]
scraped_customer_df[scraped_customer_df['confidence_score']<=0.2]

len(scraped_customer_df[scraped_customer_df['confidence_score']<=0.15])

max(scraped_customer_df['confidence_score'])

min(scraped_customer_df['confidence_score'])

