# -*- coding: utf-8 -*-
"""FinanceTableUrl.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1paM-FL0BVMaUKOl0ocszWvbJj-nikQb4
"""

!pip install selenium

!pip install bs4

from bs4 import BeautifulSoup

import os

filename_ar = os.listdir("/content/drive/MyDrive/10k extracted/RAW_FILINGS")

filename_ar = [x for x in filename_ar if x.split("_")[1] == "10K"]

filename_ar[0:5]

import requests

baseUrl = r"https://www.sec.gov/Archives/edgar/data/"

mdf = pd

from selenium import WebDriver

temp_arr = []

for f in filename_ar:
  cik = f.split("_")[0]
  accno = f.split("_")[-1].split(".")[0].split("-")
  accno  = "".join(accno)
  url = baseUrl+cik+"/"+accno+"/"+"Financial_Report.xlsx"
  temp_arr.append(url)
  # print(url)
  # hdr = {'user-agent': 'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Mobile Safari/537.36'}
  # req = requests.get(url, headers=hdr, allow_redirects = True)
  # content = req.content
  # x = requests.get(url)
  # type(x)
  print(content)

temp_arr[0:4]

import pandas as pd

df = pd.DataFrame()

df["url"] = temp_arr

df.head()

df.to_csv("finance_reports_url.csv", index = False)

soup = BeautifulSoup(content, "html.parser")

print(soup.prettify())

