# Generated by Django 3.2.8 on 2022-03-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_keymetric_metric_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keymetric',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='keymetric',
            name='year',
        ),
    ]
