# Generated by Django 3.2.8 on 2022-03-08 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220308_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='baskets',
        ),
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='baskets', to='core.user'),
            preserve_default=False,
        ),
    ]
