# -*- coding: utf-8 -*-
"""analysing_metadata_from_edgar_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y4p7zk7mMOfUWYPGwN5tjZun8k1q6aGW
"""

from bs4 import BeautifulSoup

# f = open("datasets/RAW_FILINGS/769397_10K_2021_0000769397-21-000014.htm", "r")
# f2 = open("datasets/RAW_FILINGS/796343_10K_2020_0000796343-21-000004.htm", "r")
# f3 = open("datasets/RAW_FILINGS/32034010K2020_https___www.htm", "r")
# f3 = open("datasets/RAW_FILINGS/113155410K2020_https___www.htm","r")
# f3 = open("datasets/RAW_FILINGS/89687810K2021_https___www.htm","r")
f3 = open("datasets/RAW_FILINGS/32034010K2020_https___www.htm","r")

"""APPLIED VISUAL SCIENCES INC,873198,ZUO

INTUIT INC,896878,ZUO

INTELLIGENT SYSTEM CORP,320340,ZUO

SYNCHRONOSS TECHNOLOGIES,1131554,ZUO

ROSETTA STONE INC,1351285,ZUO
"""

import json
import re

soup = BeautifulSoup(f3, "xml")

print(soup.prettify())

divt = soup.find_all("div")

pattern = re.compile(r"customer")

pattern2 = re.compile(r"\b\d[\d,.]*\b")

pattern3 = re.compile(r"\b(\d{+}|.)\b")

pattern = re.compile(r"\d customer")

ar = []
ar2 = []
ar3 = []
for div in divt:
    if div.string:
        matches = pattern.finditer(div.string)
        temp = list(matches)
        
        if temp:
            ar.append(temp)
            ar3.append(div.string) 
            matches2 = pattern2.finditer(div.string)
            # print(div.string)
            temp2 = list(matches2)
            if temp2:
                # print(temp2)
                ar2.append(div.string)

print(len(ar2))
print(len(ar3))

for arx in ar2:
    print(arx)
    print()

for arx in ar3:
    print(arx)
    print()



"""Our platforms and solutions are built in a modular fashion, thereby conducive to be extended dynamically and enabling our customers to offer solutions that are relevant to current market situations, with the goal of providing them with the competitive edge required for them to be successful.  We support expanding transaction volumes reliably and cost effectively with platforms built to scale. Our Synchronoss Personal Cloud platform is deployed across more than 95 million devices, managing 20 billion entities in the Cloud and performing more than 4 million synchronizations per day. - 1131554

In August 2020, we reorganized certain technology and customer success functions that support and benefit our overall platform. Additionally, certain legal, facility and employee service costs are now managed at the corporate level. As a result, these costs are no longer included in segment operating income and are now included in other corporate expenses. For the twelve months ended July 31, 2020 and 2019, we reclassified $180 million and $172 million from Small Business & Self-Employed, $121 million and $78 million from Consumer, and $13 million and $12 million from ProConnect to other corporate expenses. In August 2020, we also renamed our Strategic Partner segment as the ProConnect segment. This segment continues to serve professional accountants. 

Online Ecosystem revenue increased $568 million or 26% in fiscal 2021 compared with fiscal 2020. QuickBooks Online Accounting revenue increased 25% in fiscal 2021 compared with fiscal 2020 primarily due to an increase in customers, a shift in mix to our higher priced offerings and higher effective prices. Online Services revenue increased 27% in fiscal 2021 compared with fiscal 2020 primarily due to an increase in revenue from our payments and payroll offerings. Online payments revenue increased due to an increase in customers and an increase in charge volume per customer. Online payroll revenue increased due to an increase in customers and a shift in mix to our full service offering.

Desktop Ecosystem revenue increased $70 million in fiscal 2021 compared with fiscal 2020 primarily due to growth in our QuickBooks Desktop Enterprise subscription offering due to an increase in customers and higher revenue for our desktop payments offering due to higher charge volume. Also, during fiscal 2021 there was an increase in revenue from license updates as a result of price increases that occurred during fiscal 2020. These increases were partially offset by a decline in desktop unit revenue.

Revenue for our ProConnect segment increased $24 million or 5% in fiscal 2021 compared with fiscal 2020 primarily due to a higher average revenue per customer and customer growth.
- 896878




"""

divt = soup.find_all("div")

pattern = re.compile(r"customer")
pattern2 = re.compile(r"\b\d[\d,.]*\b")
pattern3 = re.compile(r"\b(\d{+}|.)\b")
ar = []
ar2 = []
ar3 = []
for div in divt:
    if div.string:
        matches = pattern.finditer(div.string)
        temp = list(matches)
        
        if temp:
            ar.append(temp)
            ar3.append(div.string) 
            matches2 = pattern2.finditer(div.string)
            # print(div.string)
            temp2 = list(matches2)
            if temp2:
                # print(temp2)
                ar2.append(div.string)