# -*- coding: utf-8 -*-
"""extracting_data_from_outside_source.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qwHfPFtXMwm7CyWba0S-iQemMnd6MztT
"""

import os
import json

import pandas as pd

df = pd.DataFrame()
  
print(df)

directory = "yahoo_finance_data"

ciks = []
dates = []
total_revenue = []
cost_of_revenue = []
gross_profit = []
gross_margin = []
filenames = []

for filename in os.listdir(directory):
    ff = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(ff):
        f = open(str(ff),"r")
        strr = filename
        l = len(strr)
        stra = strr[:l-4]
        type = stra[-1]
        print(type)
        cik = stra[:len(stra)-2]
        print(cik)
        print(filename)
        df1 = pd.read_csv(str(ff))
        # df1.replace({'-': '0'}, regex=True)
        for col in range(len(df1.columns)):
            for row in range(len(df1)):
                if df1.iloc[row][col]=='-':
                    df1.iloc[row][col] = '0'
        # df1.drop("Unnamed: 0", axis = 1)
        # df1.drop(df.columns[[0,1]], axis = 1, inplace = True)
        if type == '0':
            for j in range(2,len(df1.columns)):
                date = df1.columns[j]
                dates.append(date)
                total_revenue.append(df1.iloc[0][j])
                cost_of_revenue.append(df1.iloc[1][j])
                gross_profit.append(df1.iloc[2][j])
                gm=0
                if df1.iloc[0][j]!='-' and df1.iloc[1][j]!='-' and df1.iloc[2][j]!='-' and float(df1.iloc[0][j])!=0.0:
                    gm = (float(df1.iloc[0][j])-float(df1.iloc[1][j]))/(float(df1.iloc[0][j]))
                gross_margin.append(gm)
                ciks.append(cik)
                filenames.append(filename)

df = pd.DataFrame()

df['cik'] = ciks
df['date'] = dates
df['total revenue'] = total_revenue
df['cost of revenue'] = cost_of_revenue
df['gross_profit'] = gross_profit
df['gross_margin'] = gross_margin
df['filenames'] = filenames

"""['Unnamed: 0', 'Breakdown', 'ttm', '12/30/2020', '12/30/2019',
       '12/30/2018']
"""

df

df.to_csv('total_revenue_costofrevenue_grossprofit_grossmargin.csv')



directory = "yahoo_finance_data"

ciks = []
dates = []
total_assets = []
total_liabilities = []
total_equity = []
capitalization = []
filenames = []

for filename in os.listdir(directory):
    ff = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(ff):
        f = open(str(ff),"r")
        strr = filename
        l = len(strr)
        stra = strr[:l-4]
        type = stra[-1]
        print(type)
        cik = stra[:len(stra)-2]
        print(cik)
        print(filename)
        df1 = pd.read_csv(str(ff))
        # df1.replace({'-': '0'}, regex=True)
        for col in range(len(df1.columns)):
            for row in range(len(df1)):
                if df1.iloc[row][col]=='-':
                    df1.iloc[row][col] = '0'
        # df1.drop("Unnamed: 0", axis = 1)
        # df1.drop(df.columns[[0,1]], axis = 1, inplace = True)
        if type == '1':
            for j in range(2,len(df1.columns)):
                date = df1.columns[j]
                dates.append(date)
                total_assets.append(df1.iloc[0][j])
                total_liabilities.append(df1.iloc[1][j])
                total_equity.append(df1.iloc[2][j])
                capitalization.append(df1.iloc[3][j])

                ciks.append(cik)
                filenames.append(filename)

df = pd.DataFrame()

df['cik'] = ciks
df['date'] = dates
df['total_assets'] = total_assets
df['total_liabilities'] = total_liabilities
df['total_equity'] = total_equity
df['capitalization'] = capitalization
df['filenames'] = filenames

df

df.to_csv('annual_assets_liabilities_equity_capitalization.csv')

"""Operating Cash Flow
Investing Cash Flow
Financing Cash Flow

"""

directory = "yahoo_finance_data"

ciks = []
dates = []
operatingcf = []
investingcf = []
financingcf = []
# capitalization = []
filenames = []

for filename in os.listdir(directory):
    ff = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(ff):
        f = open(str(ff),"r")
        strr = filename
        l = len(strr)
        stra = strr[:l-4]
        type = stra[-1]
        print(type)
        cik = stra[:len(stra)-2]
        print(cik)
        print(filename)
        df1 = pd.read_csv(str(ff))
        # df1.replace({'-': '0'}, regex=True)
        for col in range(len(df1.columns)):
            for row in range(len(df1)):
                if df1.iloc[row][col]=='-':
                    df1.iloc[row][col] = '0'
        # df1.drop("Unnamed: 0", axis = 1)
        # df1.drop(df.columns[[0,1]], axis = 1, inplace = True)
        if type == '2':
            for j in range(2,len(df1.columns)):
                date = df1.columns[j]
                dates.append(date)
                operatingcf.append(df1.iloc[0][j])
                investingcf.append(df1.iloc[1][j])
                financingcf.append(df1.iloc[2][j])

                ciks.append(cik)
                filenames.append(filename)


df = pd.DataFrame()

df['cik'] = ciks
df['date'] = dates
df['Operating Cash Flow'] = operatingcf
df['Investing Cash Flow'] = investingcf
df['Financing Cash Flow'] = financingcf
# df['capitalization'] = capitalization
df['filenames'] = filenames

df

df.to_csv('allcashflows_annual.csv')