# -*- coding: utf-8 -*-
"""outside_src_scraping_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B0OHDPqC8i2gc8nJ3L1wD0reIH-qKjTj
"""

from yahooquery import Ticker
import pandas as pd

aapl = Ticker('aapl')
googl = Ticker('googl')
tickers = [aapl, googl]

aapl.balance_sheet()